backend:
  name: github
  repo: AngelSantos36/Repositorio
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "portfolio"
    label: "Portafolio"
    file: "content/portfolio.json"
    format: "json"
    fields:
      - label: "Trabajos"
        name: "items"
        widget: "list"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Tipo", name: "type", widget: "select", options: ["video","foto"] }
          - { label: "Categoría", name: "category", widget: "string", required: false }
          - { label: "Imagen portada", name: "cover", widget: "image", required: false }
          - { label: "Link", name: "link", widget: "string", required: false }
          - { label: "Descripción", name: "desc", widget: "text", required: false }
